


library(dplyr)

D <- read.csv(file.choose(), header=T, sep="\t")
barplot(D,beside=TRUE)
rownames(D) <- D$Sample.Name

D <- D[,-1]

df_max <- D  %>%
  mutate(Low_Quality=ifelse(Mean.target.coverage==min(Mean.target.coverage), "1", "0"))


layout(matrix(c(1:2), nrow=1, byrow=FALSE))

layout.show(2)

legend(x = "top", legend = colnames(D), bty = "n", ncol = 1, inset = -0.15)

barplot(t(as.matrix(D[, 1])), 
        beside = TRUE,
        names.arg = rownames(D),
        legend.text = TRUE,
        ylim = c(0,500),
        ylab = "Mean target coverage ",
        las = 3)
abline(h = c(100, 30),
       col = c("#956565", "#640B0B"),
       lwd = 2,
       lty = 2:3)

legend(x = "top", legend = colnames(D), bty = "n", ncol = 1, inset = -0.15)

barplot(t(as.matrix(D[, 2])), 
        beside = TRUE,
        names.arg = rownames(D),
        legend.text = TRUE,
        ylim = c(0,200),
        ylab = "Total million reads",
        las = 3)

abline(h = 10,
       col = "#640B0B",
       lwd = 2,
       lty = 2:3)

#################################################################################################################

W <- read.csv(file.choose(), header=T, sep="\t")
rownames(W) <- W$Sample.Name

W <- W[,-1]

df_max <- W  %>%
  mutate(Low_Quality=ifelse(Mean.target.coverage==min(Mean.target.coverage), "1", "0"))


layout(matrix(c(1:2), nrow=1, byrow=FALSE))

layout.show(2)

legend(x = "top", legend = colnames(W), bty = "n", ncol = 1, inset = -0.15)

barplot(t(as.matrix(W[, 1])), 
        beside = TRUE,
        names.arg = rownames(W),
        legend.text = TRUE,
        ylim = c(0,50),
        ylab = "Mean target coverage ",
        las = 3)
abline(h = 25,
       col = "#640B0B",
       lwd = 2,
       lty = 2:3)

legend(x = "top", legend = colnames(W), bty = "n", ncol = 1, inset = -0.15)

barplot(t(as.matrix(W[, 2])), 
        beside = TRUE,
        names.arg = rownames(W),
        legend.text = TRUE,
        col = "grey",
        ylim = c(0,50),
        ylab = "Total million reads",
        las = 3)

abline(h = 10,
       col = "#640B0B",
       lwd = 2,
       lty = 2:3)

####################################################################################################################
# CORRELATION AGE-COVERAGE
A <- read.csv(file.choose(), header=T, sep="\t")

rownames(A) <- A$Sample.Name
A <- A[,-1]

#prueba normalidad
for (i in 1:2){print(shapiro.test(A[,i]))} # They both follow a normal distribution

corMatMy <- cor(A, method= "pearson")
corMatMy <- as.matrix(corMatMy)
corMatMy

library(corrplot)
corrplot(corMatMy, order = "hclust", tl.cex = 0.9, tl.col = "darkblue", mar=c(0,0,1,0), font.main = 2)
corrplot(corMatMy)
# Are these correlations significatives?

Mean_target_coverage <- A$Mean.target.coverage
Age_FFPE_tissue <- A$Age.FFPE.tissue

res <- cor.test(x=Mean_target_coverage, y=Age_FFPE_tissue, method="pearson")
res$p.value
res$estimate

# Scatter plot with correlation coefficient:

library(ggpubr)
A <- A[,c(1,3)]
sp <- ggscatter(A, x = "Age.FFPE.tissue", y = "Mean.target.coverage",
                add = "reg.line",  # Add regressin line
                add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
                conf.int = TRUE, # Add confidence interval
                xlim = c(1995, 2014)
)

# Add correlation coefficient
sp + stat_cor(method = "pearson", label.x = 2000)
#> `geom_smooth()` using formula 'y ~ x'
